version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: localpw
      POSTGRES_DB: local_dev
    ports:
      - "5433:5432"